# Site settings
title: Beachwood High School Computer Science Club
description: Official portfolio
# User settings
username: Beachwood High School Computer Science Club
user_description: We are Beachwood High School's Computer Science Club.
user_title: We do computer things
email: 23kmalhotra@beachwoodstudents.org
# twitter_username: lorem_ipsum
github_username: beachwood-high-school
# gplus_username:  lorem_ipsum
closing: Built with Jekyll and a theme by <a href="https://github.com/murraco">Mauricio Urraco</a> and this instance coded by BHSCS students
youtubeurl: https://www.youtube.com/channel/UCgYgYy_LWyq8-M3JVvRA47Q